# Generated by Django 4.2.7 on 2023-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0002_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='imagesPizzas/delfault.PNG', upload_to='imagesPizzas/'),
        ),
    ]
